# United States - Crime Rates - 1960 - 2014

### Introduction:

This time you will create a data 

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv).

### Step 3. Assign it to a variable called crime.

In [2]:
crime = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv')

### Step 4. What is the type of the columns?

In [4]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 12 columns):
Year                  55 non-null int64
Population            55 non-null int64
Total                 55 non-null int64
Violent               55 non-null int64
Property              55 non-null int64
Murder                55 non-null int64
Forcible_Rape         55 non-null int64
Robbery               55 non-null int64
Aggravated_assault    55 non-null int64
Burglary              55 non-null int64
Larceny_Theft         55 non-null int64
Vehicle_Theft         55 non-null int64
dtypes: int64(12)
memory usage: 5.3 KB

##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64

In [7]:
crime['Year'] =  pd.to_datetime(crime['Year'])
crime

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1970-01-01 00:00:00.000001960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1970-01-01 00:00:00.000001961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1970-01-01 00:00:00.000001962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
3,1970-01-01 00:00:00.000001963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
4,1970-01-01 00:00:00.000001964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800
5,1970-01-01 00:00:00.000001965,193526000,4739400,387390,4352000,9960,23410,138690,215330,1282500,2572600,496900
6,1970-01-01 00:00:00.000001966,195576000,5223500,430180,4793300,11040,25820,157990,235330,1410100,2822000,561200
7,1970-01-01 00:00:00.000001967,197457000,5903400,499930,5403500,12240,27620,202910,257160,1632100,3111600,659800
8,1970-01-01 00:00:00.000001968,199399000,6720200,595010,6125200,13800,31670,262840,286700,1858900,3482700,783600
9,1970-01-01 00:00:00.000001969,201385000,7410900,661870,6749000,14760,37170,298850,311090,1981900,3888600,878500
10,1970-01-01 00:00:00.000001970,203235298,8098000,738820,7359200,16000,37990,349860,334970,2205000,4225800,928400
11,1970-01-01 00:00:00.000001971,206212000,8588200,816500,7771700,17780,42260,387700,368760,2399300,4424200,948200
12,1970-01-01 00:00:00.000001972,208230000,8248800,834900,7413900,18670,46850,376290,393090,2375500,4151200,887200
13,1970-01-01 00:00:00.000001973,209851000,8718100,875910,7842200,19640,51400,384220,420650,2565500,4347900,928800
14,1970-01-01 00:00:00.000001974,211392000,10253400,974720,9278700,20710,55400,442400,456210,3039200,5262500,977100
15,1970-01-01 00:00:00.000001975,213124000,11292400,1039710,10252700,20510,56090,470500,492620,3265300,5977700,1009600
16,1970-01-01 00:00:00.000001976,214659000,11349700,1004210,10345500,18780,57080,427810,500530,3108700,6270800,966000
17,1970-01-01 00:00:00.000001977,216332000,10984500,1029580,9955000,19120,63500,412610,534350,3071500,5905700,977700
18,1970-01-01 00:00:00.000001978,218059000,11209000,1085550,10123400,19560,67610,426930,571460,3128300,5991000,1004100
19,1970-01-01 00:00:00.000001979,220099000,12249500,1208030,11041500,21460,76390,480700,629480,3327700,6601000,1112800
20,1970-01-01 00:00:00.000001980,225349264,13408300,1344520,12063700,23040,82990,565840,672650,3795200,7136900,1131700
21,1970-01-01 00:00:00.000001981,229146000,13423800,1361820,12061900,22520,82500,592910,663900,3779700,7194400,1087800
22,1970-01-01 00:00:00.000001982,231534000,12974400,1322390,11652000,21010,78770,553130,669480,3447100,7142500,1062400
23,1970-01-01 00:00:00.000001983,233981000,12108600,1258090,10850500,19310,78920,506570,653290,3129900,6712800,1007900
24,1970-01-01 00:00:00.000001984,236158000,11881800,1273280,10608500,18690,84230,485010,685350,2984400,6591900,1032200
25,1970-01-01 00:00:00.000001985,238740000,12431400,1328800,11102600,18980,88670,497870,723250,3073300,6926400,1102900
26,1970-01-01 00:00:00.000001986,240132887,13211869,1489169,11722700,20613,91459,542775,834322,3241410,7257153,1224137
27,1970-01-01 00:00:00.000001987,242282918,13508700,1483999,12024700,20096,91110,517704,855088,3236184,7499900,1288674
28,1970-01-01 00:00:00.000001988,245807000,13923100,1566220,12356900,20680,92490,542970,910090,3218100,7705900,1432900
29,1970-01-01 00:00:00.000001989,248239000,14251400,1646040,12605400,21500,94500,578330,951710,3168200,7872400,1564800
30,1970-01-01 00:00:00.000001990,248709873,14475600,1820130,12655500,23440,102560,639270,1054860,3073900,7945700,1635900
31,1970-01-01 00:00:00.000001991,252177000,14872900,1911770,12961100,24700,106590,687730,1092740,3157200,8142200,1661700
32,1970-01-01 00:00:00.000001992,255082000,14438200,1932270,12505900,23760,109060,672480,1126970,2979900,7915200,1610800
33,1970-01-01 00:00:00.000001993,257908000,14144800,1926020,12218800,24530,106010,659870,1135610,2834800,7820900,1563100
34,1970-01-01 00:00:00.000001994,260341000,13989500,1857670,12131900,23330,102220,618950,1113180,2712800,7879800,1539300
35,1970-01-01 00:00:00.000001995,262755000,13862700,1798790,12063900,21610,97470,580510,1099210,2593800,7997700,1472400
36,1970-01-01 00:00:00.000001996,265228572,13493863,1688540,11805300,19650,96250,535590,1037050,2506400,7904700,1394200
37,1970-01-01 00:00:00.000001997,267637000,13194571,1634770,11558175,18208,96153,498534,1023201,2460526,7743760,1354189
38,1970-01-01 00:00:00.000001998,270296000,12475634,1531044,10944590,16914,93103,446625,974402,2329950,7373886,1240754
39,1970-01-01 00:00:00.000001999,272690813,11634378,1426044,10208334,15522,89411,409371,911740,2100739,6955520,1152075
40,1970-01-01 00:00:00.000002000,281421906,11608072,1425486,10182586,15586,90178,408016,911706,2050992,6971590,1160002
41,1970-01-01 00:00:00.000002001,285317559,11876669,1439480,10437480,16037,90863,423557,909023,2116531,7092267,1228391
42,1970-01-01 00:00:00.000002002,287973924,11878954,1423677,10455277,16229,95235,420806,891407,2151252,7057370,1246646
43,1970-01-01 00:00:00.000002003,290690788,11826538,1383676,10442862,16528,93883,414235,859030,2154834,7026802,1261226
44,1970-01-01 00:00:00.000002004,293656842,11679474,1360088,10319386,16148,95089,401470,847381,2144446,6937089,1237851
45,1970-01-01 00:00:00.000002005,296507061,11565499,1390745,10174754,16740,94347,417438,862220,2155448,6783447,1235859
46,1970-01-01 00:00:00.000002006,299398484,11401511,1418043,9983568,17030,92757,447403,860853,2183746,6607013,1192809
47,1970-01-01 00:00:00.000002007,301621157,11251828,1408337,9843481,16929,90427,445125,855856,2176140,6568572,1095769
48,1970-01-01 00:00:00.000002008,304374846,11160543,1392628,9767915,16442,90479,443574,842134,2228474,6588046,958629
49,1970-01-01 00:00:00.000002009,307006550,10762956,1325896,9337060,15399,89241,408742,812514,2203313,6338095,795652
50,1970-01-01 00:00:00.000002010,309330219,10363873,1251248,9112625,14772,85593,369089,781844,2168457,6204601,739565
51,1970-01-01 00:00:00.000002011,311587816,10258774,1206031,9052743,14661,84175,354772,752423,2185140,6151095,716508
52,1970-01-01 00:00:00.000002012,313873685,10219059,1217067,9001992,14866,85141,355051,762009,2109932,6168874,723186
53,1970-01-01 00:00:00.000002013,316497531,9850445,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294
54,1970-01-01 00:00:00.000002014,318857056,9475816,1197987,8277829,14249,84041,325802,741291,1729806,5858496,689527

### Step 6. Set the Year column as the index of the dataframe

In [9]:
crime.set_index('Year')

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1970-01-01 00:00:00.000001960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1970-01-01 00:00:00.000001961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
1970-01-01 00:00:00.000001962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
1970-01-01 00:00:00.000001963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
1970-01-01 00:00:00.000001964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800
1970-01-01 00:00:00.000001965,193526000,4739400,387390,4352000,9960,23410,138690,215330,1282500,2572600,496900
1970-01-01 00:00:00.000001966,195576000,5223500,430180,4793300,11040,25820,157990,235330,1410100,2822000,561200
1970-01-01 00:00:00.000001967,197457000,5903400,499930,5403500,12240,27620,202910,257160,1632100,3111600,659800
1970-01-01 00:00:00.000001968,199399000,6720200,595010,6125200,13800,31670,262840,286700,1858900,3482700,783600
1970-01-01 00:00:00.000001969,201385000,7410900,661870,6749000,14760,37170,298850,311090,1981900,3888600,878500
1970-01-01 00:00:00.000001970,203235298,8098000,738820,7359200,16000,37990,349860,334970,2205000,4225800,928400
1970-01-01 00:00:00.000001971,206212000,8588200,816500,7771700,17780,42260,387700,368760,2399300,4424200,948200
1970-01-01 00:00:00.000001972,208230000,8248800,834900,7413900,18670,46850,376290,393090,2375500,4151200,887200
1970-01-01 00:00:00.000001973,209851000,8718100,875910,7842200,19640,51400,384220,420650,2565500,4347900,928800
1970-01-01 00:00:00.000001974,211392000,10253400,974720,9278700,20710,55400,442400,456210,3039200,5262500,977100
1970-01-01 00:00:00.000001975,213124000,11292400,1039710,10252700,20510,56090,470500,492620,3265300,5977700,1009600
1970-01-01 00:00:00.000001976,214659000,11349700,1004210,10345500,18780,57080,427810,500530,3108700,6270800,966000
1970-01-01 00:00:00.000001977,216332000,10984500,1029580,9955000,19120,63500,412610,534350,3071500,5905700,977700
1970-01-01 00:00:00.000001978,218059000,11209000,1085550,10123400,19560,67610,426930,571460,3128300,5991000,1004100
1970-01-01 00:00:00.000001979,220099000,12249500,1208030,11041500,21460,76390,480700,629480,3327700,6601000,1112800
1970-01-01 00:00:00.000001980,225349264,13408300,1344520,12063700,23040,82990,565840,672650,3795200,7136900,1131700
1970-01-01 00:00:00.000001981,229146000,13423800,1361820,12061900,22520,82500,592910,663900,3779700,7194400,1087800
1970-01-01 00:00:00.000001982,231534000,12974400,1322390,11652000,21010,78770,553130,669480,3447100,7142500,1062400
1970-01-01 00:00:00.000001983,233981000,12108600,1258090,10850500,19310,78920,506570,653290,3129900,6712800,1007900
1970-01-01 00:00:00.000001984,236158000,11881800,1273280,10608500,18690,84230,485010,685350,2984400,6591900,1032200
1970-01-01 00:00:00.000001985,238740000,12431400,1328800,11102600,18980,88670,497870,723250,3073300,6926400,1102900
1970-01-01 00:00:00.000001986,240132887,13211869,1489169,11722700,20613,91459,542775,834322,3241410,7257153,1224137
1970-01-01 00:00:00.000001987,242282918,13508700,1483999,12024700,20096,91110,517704,855088,3236184,7499900,1288674
1970-01-01 00:00:00.000001988,245807000,13923100,1566220,12356900,20680,92490,542970,910090,3218100,7705900,1432900
1970-01-01 00:00:00.000001989,248239000,14251400,1646040,12605400,21500,94500,578330,951710,3168200,7872400,1564800
1970-01-01 00:00:00.000001990,248709873,14475600,1820130,12655500,23440,102560,639270,1054860,3073900,7945700,1635900
1970-01-01 00:00:00.000001991,252177000,14872900,1911770,12961100,24700,106590,687730,1092740,3157200,8142200,1661700
1970-01-01 00:00:00.000001992,255082000,14438200,1932270,12505900,23760,109060,672480,1126970,2979900,7915200,1610800
1970-01-01 00:00:00.000001993,257908000,14144800,1926020,12218800,24530,106010,659870,1135610,2834800,7820900,1563100
1970-01-01 00:00:00.000001994,260341000,13989500,1857670,12131900,23330,102220,618950,1113180,2712800,7879800,1539300
1970-01-01 00:00:00.000001995,262755000,13862700,1798790,12063900,21610,97470,580510,1099210,2593800,7997700,1472400
1970-01-01 00:00:00.000001996,265228572,13493863,1688540,11805300,19650,96250,535590,1037050,2506400,7904700,1394200
1970-01-01 00:00:00.000001997,267637000,13194571,1634770,11558175,18208,96153,498534,1023201,2460526,7743760,1354189
1970-01-01 00:00:00.000001998,270296000,12475634,1531044,10944590,16914,93103,446625,974402,2329950,7373886,1240754
1970-01-01 00:00:00.000001999,272690813,11634378,1426044,10208334,15522,89411,409371,911740,2100739,6955520,1152075
1970-01-01 00:00:00.000002000,281421906,11608072,1425486,10182586,15586,90178,408016,911706,2050992,6971590,1160002
1970-01-01 00:00:00.000002001,285317559,11876669,1439480,10437480,16037,90863,423557,909023,2116531,7092267,1228391
1970-01-01 00:00:00.000002002,287973924,11878954,1423677,10455277,16229,95235,420806,891407,2151252,7057370,1246646
1970-01-01 00:00:00.000002003,290690788,11826538,1383676,10442862,16528,93883,414235,859030,2154834,7026802,1261226
1970-01-01 00:00:00.000002004,293656842,11679474,1360088,10319386,16148,95089,401470,847381,2144446,6937089,1237851
1970-01-01 00:00:00.000002005,296507061,11565499,1390745,10174754,16740,94347,417438,862220,2155448,6783447,1235859
1970-01-01 00:00:00.000002006,299398484,11401511,1418043,9983568,17030,92757,447403,860853,2183746,6607013,1192809
1970-01-01 00:00:00.000002007,301621157,11251828,1408337,9843481,16929,90427,445125,855856,2176140,6568572,1095769
1970-01-01 00:00:00.000002008,304374846,11160543,1392628,9767915,16442,90479,443574,842134,2228474,6588046,958629
1970-01-01 00:00:00.000002009,307006550,10762956,1325896,9337060,15399,89241,408742,812514,2203313,6338095,795652
1970-01-01 00:00:00.000002010,309330219,10363873,1251248,9112625,14772,85593,369089,781844,2168457,6204601,739565
1970-01-01 00:00:00.000002011,311587816,10258774,1206031,9052743,14661,84175,354772,752423,2185140,6151095,716508
1970-01-01 00:00:00.000002012,313873685,10219059,1217067,9001992,14866,85141,355051,762009,2109932,6168874,723186
1970-01-01 00:00:00.000002013,316497531,9850445,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294
1970-01-01 00:00:00.000002014,318857056,9475816,1197987,8277829,14249,84041,325802,741291,1729806,5858496,689527

### Step 7. Delete the Total column

In [11]:
crime.drop("Total", inplace=True, axis= 1 )

In [13]:
crime.head(3)

,Year,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1970-01-01 00:00:00.000001960,179323175,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1970-01-01 00:00:00.000001961,182992000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1970-01-01 00:00:00.000001962,185771000,301510,3450700,8530,17550,110860,164570,994300,2089600,366800

### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake

### Step 9. What is the most dangerous decade to live in the US?

(55, 11)